### ISSUE TITLE
Dell C2665dnf Color MFP Detects but fails to setup

### ISSUE THREAD

**Issue by nathan-curtis** [kongo09/hass-dell-printer#6]
HA 2022.07.0 Supervised

This build detected my Dell C2665dnf Color MFP (nice job - I've been trying to get this setup unsuccessfully with the IPP integration)

The printer is detected but fails to setup with the following error in the log:
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/dell_printer/__init__.py:34
Integration: Dell Printer (documentation, issues)
First occurred: 10:23:52 AM (1 occurrences)
Last logged: 10:23:52 AM

Error setting up entry Dell C2665dnf Color MFP for dell_printer
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 353, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/dell_printer/__init__.py", line 34, in async_setup_entry
    await printer.load_data()
  File "/usr/local/lib/python3.10/site-packages/dell_printer_parser/printer_parser.py", line 31, in load_data
    await self._set_language()
  File "/usr/local/lib/python3.10/site-packages/dell_printer_parser/printer_parser.py", line 45, in _set_language
    response.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 404, message='Not found', url=URL('http://192.168.1.120/default.asp?Lang=en-us')

Checking the URL given in the message above reports a 404 from all browsers on my network.  THat url does not exist on this printer (current firmware - also the last firmware released for this printer - it won't be upgraded.)

The printer DOES respond on:
http://[192.168.1.120/index.htm](http://192.168.1.120/index.htm)
or
http://[192.168.1.120/index.htm?Lang=en-us](http://192.168.1.120/index.htm?Lang=en-us)

trying to login to the incorrect default page for this model perhaps?

The log goes on to attempt to detect the printer on its IPv6 Address as well, then fails with a different error about invalid URLs and IPV6 addresses.

**Comment by kongo09** [comment]
Thanks for reporting this. The integration was never intended for this model. It actually parses the web interface to get its data.

Feel free to paste your HTML from that interface and I can take a look how similar it is.

**Comment by nathan-curtis** [comment]
Sure thing:
Page source:
```
<html>
<body>
<!--StartFragment-->

<html>
--
  | <head>
  | <title>
  | </title>
  | </head>
  |  
  | <frameset cols="220,*" border=0>
  | <frame src="frameleft.htm" name="TopFrame" title="main" frameborder=0 scrolling=auto>
  | <frameset rows="32,*" border=0>
  | <frame src="framelogo.htm" name="TopLogo" title="logo" frameborder=0 scrolling=no noresize>
  | <frameset rows="140,*" border=0>
  | <frame src="frametop.htm" name="LeftFrame" title="header" frameborder=0 scrolling=no noresize>
  | <frame src="status/status.htm" name="RightFrame" title="contents" frameborder=0>
  | </frameset>
  | </frameset>
  | </frameset>
  |  
  | </html>

<!--EndFragment-->
</body>
</html>
```
Top Status Panel
```
<html>
<head>
<meta http-equiv="Refresh" content="30">
<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
<meta http-equiv="Content-Style-Type" content="text/css">
<STYLE TYPE="text/css"><!--
body { font-family: Arial, Helvetica, sans-serif, Verdana; margin-left:0; margin-right:0; margin-top:0; margin-bottom:0; }
--></STYLE>
<link rel="stylesheet" href="common_dell.css" type="text/css">
<title>Dell C2665dnf Color MFP</title>
</head>
<body  bgcolor="#ffffff"  link="#FFFFFF" alink="#FFFFFF" vlink="#FFFFFF">
<style type="text/css">
<!--
body { margin-left:0; margin-right:0; margin-top:0; margin-bottom:0; border-bottom:1px ridge #666666; }
-->
</style>

<div style="position:absolute; top:0px; left:0px; width:295px; height:140px; overflow:auto">
<table border=0 class=topframe>
<tr><td class=top_product><font size=+1>Dell C2665dnf Color MFP</font></td></tr>
<tr><td class=top_nowrap>IPv4: 192.168.1.120<br>
IPv6(Stateless 1): REDACTED/64<br>
IPv6(Stateful 1): REDACTED/64<br>
IPv6(Link Local): REDACTED<br>
</td></tr>
<tr><td class=topfrm>Location: Back Office</td></tr>
<tr><td class=topfrm>Contact Person: REDACTED</td></tr>
</table>
</div>
<div style="position:absolute; top:2px;  left:340px; width:280px; height:140px; overflow-y:auto">
<table border=0  width=250px><tr><td>
<table  border=0 cellspacing=0 cellpadding=0 width=100% class=lcdpnl id="greenpnl">
<tr align="left" valign=top><td  id=console>Ready</td>
</tr>
<tr><td nowrap><table border=0 cellspacing=0 cellpadding=0 width=100%><tr height=2><td></td></tr></table></td></tr>
</table>
</td></tr></table></div>
<div style="position:absolute; top:20px; left:650px; ">
<a href="status/status.htm" target="RightFrame">
<img src="images/c2665_tray1.png" alt="" width=100 height=100 border="0"></a>
</div>
<table style="height:100%; width:100%;"><tr><td></td></tr></table>
</body>
</html>
```
Left Menu
```
<html>
<body>
<!--StartFragment-->

  | <html>
-- | --
  | <head>
  | <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
  | <meta http-equiv="Content-Style-Type" content="text/css">
  | <STYLE TYPE="text/css"><!--
  | body { font-family: Arial, Helvetica, sans-serif, Verdana; margin-left:0; margin-right:0; margin-top:0; margin-bottom:0; }
  | --></STYLE>
  | <link rel="stylesheet" href="common_dell.css" type="text/css">
  | <title>Dell C2665dnf Color MFP</title>
  | </head>
  | <body  bgcolor="#ffffff"  link="#0033CC" alink="#0033CC" vlink="#0033CC">
  | <center><table border=0 cellspacing=2><tr><td><a href="http://www.dell.com" target=_blank><img src="images/logo0002.png" alt="" border="0"></a></td></tr></table></center><table border=0 class=leftframe_1>
  | <tr><td><table border=0 class=leftframe_2>
  | <tr><td><b><a href="status/status.htm" target=RightFrame>Printer Status</a></b></td></tr>
  | <tr><td>&nbsp;</td></tr><tr><td><b><a href="job/queue.htm" target=RightFrame>Printer Jobs</a></b></td></tr>
  | <tr><td>&nbsp;</td></tr><tr><td><b><a href="printer/prtreport.htm" target=RightFrame>Printer Settings</a></b></td></tr>
  | <tr><td>&nbsp;</td></tr><tr><td><b><a href="setting/rptsvr.htm" target=RightFrame>Print Server Settings</a></b></td></tr>
  | <tr><td>&nbsp;</td></tr><tr><td><b><a href="setting/cpyprtset.htm" target=RightFrame>Copy Printer Settings</a></b></td></tr>
  | <tr><td>&nbsp;</td></tr><tr><td><b><a href="prtmaint/prtvolume.htm" target=RightFrame>Print Volume</a></b></td></tr>
  | <tr><td>&nbsp;</td></tr><tr><td><b><a href="srvcset/emlusrlst.htm" target=RightFrame>Address Book</a></b></td></tr>
  | <tr><td>&nbsp;</td></tr><tr><td><b><a href="status/infomation.htm" target=RightFrame>Printer Information</a></b></td></tr>
  | <tr><td>&nbsp;</td></tr><tr><td><b><a href="printer/prtintray.htm" target=RightFrame>Tray Management</a></b></td></tr>
  | <tr><td>&nbsp;</td></tr><tr><td><b><a href="setting/setemalert.htm" target=RightFrame>E-Mail Server Settings Overview</a></b></td></tr>
  | <tr><td>&nbsp;</td></tr><tr><td><b><a href="setting/setews.htm" target=RightFrame>Set Password</a></b></td></tr>
  | <tr><td>&nbsp;</td></tr><tr><td><b><a href="http://support.dell.com" target=_blank>Online Help</a></b></td></tr>
  | <tr><td>&nbsp;</td></tr><tr><td><b>Order Supplies at:</b></td></tr>
  | <tr><td><b><a href="http://accessories.us.dell.com/sna/PrinterSeg.aspx?LS=en-US&DL=0&ST=DBMXF42&MD=C2665dnf&KTS=6000&KCMY=00&KTL=30&KTS2=4000&KCMY2=10&KTL2=40&KTS3=4000&KCMY3=20&KTL3=60&KTS4=4000&KCMY4=30&KTL4=30" target=_blank>www.dell.com/supplies</a></b></td></tr>
  | <tr><td>&nbsp;</td></tr><tr><td><b>Contact Dell Support at:</b></td></tr>
  | <tr><td><b><a href="http://support.dell.com" target=_blank>support.dell.com</a></b></td></tr>
  | <tr><td>&nbsp;</td></tr><tr><td><b>Dell Document Hub at:</b></td></tr>
  | <tr><td><b><a href="http://www.dell.com/dochub" target=_blank>www.dell.com/dochub</a></b></td></tr>
  | <tr><td>&nbsp;</td></tr></table>
  | </td></tr></table>
  | </body>
  | </html>

<!--EndFragment-->
</body>
</html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
<meta http-equiv="Content-Style-Type" content="text/css">
<STYLE TYPE="text/css"><!--
body { font-family: Arial, Helvetica, sans-serif, Verdana; margin-left:0; margin-right:0; margin-top:0; margin-bottom:0; }
--></STYLE>
<link rel="stylesheet" href="[common_dell.css](http://192.168.1.120/common_dell.css)" type="text/css">
<title>Dell C2665dnf Color MFP</title>
</head>
<body  bgcolor="#ffffff"  link="#0033CC" alink="#0033CC" vlink="#0033CC">
<center><table border=0 cellspacing=2><tr><td><a href="http://www.dell.com/" target=_blank><img src="[images/logo0002.png](http://192.168.1.120/images/logo0002.png)" alt="" border="0"></a></td></tr></table></center><table border=0 class=leftframe_1>
<tr><td><table border=0 class=leftframe_2>
<tr><td><b><a href="[status/status.htm](http://192.168.1.120/status/status.htm)" target=RightFrame>Printer Status</a></b></td></tr>
<tr><td>&nbsp;</td></tr><tr><td><b><a href="[job/queue.htm](http://192.168.1.120/job/queue.htm)" target=RightFrame>Printer Jobs</a></b></td></tr>
<tr><td>&nbsp;</td></tr><tr><td><b><a href="[printer/prtreport.htm](http://192.168.1.120/printer/prtreport.htm)" target=RightFrame>Printer Settings</a></b></td></tr>
<tr><td>&nbsp;</td></tr><tr><td><b><a href="[setting/rptsvr.htm](http://192.168.1.120/setting/rptsvr.htm)" target=RightFrame>Print Server Settings</a></b></td></tr>
<tr><td>&nbsp;</td></tr><tr><td><b><a href="[setting/cpyprtset.htm](http://192.168.1.120/setting/cpyprtset.htm)" target=RightFrame>Copy Printer Settings</a></b></td></tr>
<tr><td>&nbsp;</td></tr><tr><td><b><a href="[prtmaint/prtvolume.htm](http://192.168.1.120/prtmaint/prtvolume.htm)" target=RightFrame>Print Volume</a></b></td></tr>
<tr><td>&nbsp;</td></tr><tr><td><b><a href="[srvcset/emlusrlst.htm](http://192.168.1.120/srvcset/emlusrlst.htm)" target=RightFrame>Address Book</a></b></td></tr>
<tr><td>&nbsp;</td></tr><tr><td><b><a href="[status/infomation.htm](http://192.168.1.120/status/infomation.htm)" target=RightFrame>Printer Information</a></b></td></tr>
<tr><td>&nbsp;</td></tr><tr><td><b><a href="[printer/prtintray.htm](http://192.168.1.120/printer/prtintray.htm)" target=RightFrame>Tray Management</a></b></td></tr>
<tr><td>&nbsp;</td></tr><tr><td><b><a href="[setting/setemalert.htm](http://192.168.1.120/setting/setemalert.htm)" target=RightFrame>E-Mail Server Settings Overview</a></b></td></tr>
<tr><td>&nbsp;</td></tr><tr><td><b><a href="[setting/setews.htm](http://192.168.1.120/setting/setews.htm)" target=RightFrame>Set Password</a></b></td></tr>
<tr><td>&nbsp;</td></tr><tr><td><b><a href="http://support.dell.com/" target=_blank>Online Help</a></b></td></tr>
<tr><td>&nbsp;</td></tr><tr><td><b>Order Supplies at:</b></td></tr>
<tr><td><b><a href="http://accessories.us.dell.com/sna/PrinterSeg.aspx?LS=en-US&DL=0&ST=DBMXF42&MD=C2665dnf&KTS=6000&KCMY=00&KTL=30&KTS2=4000&KCMY2=10&KTL2=40&KTS3=4000&KCMY3=20&KTL3=60&KTS4=4000&KCMY4=30&KTL4=30" target=_blank>www.dell.com/supplies</a></b></td></tr>
<tr><td>&nbsp;</td></tr><tr><td><b>Contact Dell Support at:</b></td></tr>
<tr><td><b><a href="http://support.dell.com/" target=_blank>support.dell.com</a></b></td></tr>
<tr><td>&nbsp;</td></tr><tr><td><b>Dell Document Hub at:</b></td></tr>
<tr><td><b><a href="http://www.dell.com/dochub" target=_blank>www.dell.com/dochub</a></b></td></tr>
<tr><td>&nbsp;</td></tr></table>
</td></tr></table>
</body>
</html>
```
Main Frame:
```
<html>
<body>
<!--StartFragment-->

  | <html>
-- | --
  | <head>
  | <meta http-equiv="Refresh" content="30">
  | <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
  | <meta http-equiv="Content-Style-Type" content="text/css">
  | <STYLE TYPE="text/css"><!--
  | body { font-family: Arial, Helvetica, sans-serif, Verdana; margin-left:0; margin-right:0; margin-top:0; margin-bottom:0; }
  | --></STYLE>
  | <link rel="stylesheet" href="../common_dell.css" type="text/css">
  | <title>Dell C2665dnf Color MFP</title>
  | </head>
  | <body  bgcolor="#ffffff"  link="#FFFFFF" alink="#FFFFFF" vlink="#FFFFFF">
  | <table>
  | <tr><td>
  | <table border=0 cellpadding=0 cellspacing=0 width=800><tr><td>
  | <table border=0 cellpadding=0 cellspacing=0>
  | <tr>
  | <td valign=top bgcolor=#cdcdcd><div style="background-image: url(../images/lefton.gif  ); border-bottom: 1px solid rgb(255, 255, 255);  width:9px; height:36px;"></div></td>
  | <td align=center valign=middle bgcolor=#ffffff height=36 nowrap style="white-space: nowrap; border-bottom: 1px solid rgb(255, 255, 255); background-image: url(../images/topon.gif); background-repeat: repeat-x" ><b><font size=-1 color="blue">Printer Status</font></b></td>
  | <td valign=top bgcolor=#cdcdcd><div style="background-image: url(../images/righton.gif ); border-bottom: 1px solid rgb(255, 255, 255);  width:9px; height:36px;"></div></td>
  | <td bgcolor="#ffffff" valign="bottom" style="empty-cells:show; border-bottom: 1px solid rgb(0, 0, 0); width: 800; ">&nbsp;</td></tr>
  | <tr>
  | <td valign=bottom bgcolor=#ffffff width=9 height=2></td><td valign=bottom bgcolor=#ffffff width=120 height=2></td><td valign=bottom bgcolor=#ffffff width=9 height=2></td><td bgcolor="#ffffff" valign="bottom" height=2></td></tr>
  | </table>
  | </td></tr></table>
  | <table border=0 cellpadding=2 cellspacing=0><tr><td>
  | <table border=0 cellpadding=2 cellspacing=0><tr>
  | <td nowrap align=left><b><font size=-1><a href="status.htm" target="_self">Printer Status</a></font></b>
  | <b><font size=-1> \| <a href="events.htm" target="_self">Printer Events</a></font></b>
  | <b><font size=-1> \| <a href="infomation.htm" target="_self">Printer Information</a></font></b>
  | </td></tr></table>
  | </td></tr></table>
  | <hr>
  | <table><tr><td><font size=+2><b>Printer Status - </b></font>
  | <script language="JavaScript">
  | <!--
  | document.write("<input type='button' onClick=window.location='status.htm' value='Refresh'  class=refreshBtn>")
  | //-->
  | </script>
  | <noscript>
  | <font size=-1><a href="status.htm" target="_self">Refresh</a></font>
  | </noscript>
  | </td></tr></table><br><form method="post" action="status.htm"><table border=1 cellpadding=4 cellspacing=0 width=100%><tr><td nowrap>
  | <table border=0 cellpadding=2 cellspacing=0 width=100%>
  | <tr><td nowrap width=250></td><td></td></tr>
  | <tr><td nowrap><b>Cyan Toner Cartridge : OK</b></td><td nowrap></td></tr>
  | <tr><td nowrap><table frame=border border=2 cellpadding=0 cellspacing=0 bordercolor="cyan"><tr><td nowrap width=80 height=15 bgcolor="cyan">&nbsp;</td><td nowrap width=120 height=15 bgcolor="White">&nbsp;</td></tr></table>
  | </td><td></td></tr>
  | <tr><td nowrap><b>Magenta Toner Cartridge : OK</b></td><td nowrap></td></tr>
  | <tr><td nowrap><table frame=border border=2 cellpadding=0 cellspacing=0 bordercolor="magenta"><tr><td nowrap width=120 height=15 bgcolor="magenta">&nbsp;</td><td nowrap width=80 height=15 bgcolor="White">&nbsp;</td></tr></table>
  | </td><td></td></tr>
  | <tr><td nowrap><b>Yellow Toner Cartridge : OK</b></td><td nowrap></td></tr>
  | <tr><td nowrap><table frame=border border=2 cellpadding=0 cellspacing=0 bordercolor="yellow"><tr><td nowrap width=60 height=15 bgcolor="yellow">&nbsp;</td><td nowrap width=140 height=15 bgcolor="White">&nbsp;</td></tr></table>
  | </td><td></td></tr>
  | <tr><td nowrap><b>Black Toner Cartridge : OK</b></td><td nowrap></td></tr>
  | <tr><td nowrap><table frame=border border=2 cellpadding=0 cellspacing=0 bordercolor="black"><tr><td nowrap width=60 height=15 bgcolor="black">&nbsp;</td><td nowrap width=140 height=15 bgcolor="White">&nbsp;</td></tr></table>
  | </td><td></td></tr>
  | </table></td></tr></table>
  | <br><table border=1 cellpadding=4 cellspacing=0 width=100%><tr><td nowrap>
  | <table border=0 cellpadding=2 cellspacing=0 width=100%>
  | <tr><th scope="col" nowrap align="left" width=35%><b>Consumables:</b></th><th scope="col" nowrap align="left" width=15%><b>Status:</b></th><th scope="col" width=50%></th></tr>
  | <tr><td nowrap width=35%>Cyan Drum Cartridge</td><td nowrap width=15% bgcolor="Lightgreen"><b>OK</b></td><td width=50%></td></tr>
  | <tr><td nowrap width=35%>Magenta Drum Cartridge</td><td nowrap width=15% bgcolor="Lightgreen"><b>OK</b></td><td width=50%></td></tr>
  | <tr><td nowrap width=35%>Yellow Drum Cartridge</td><td nowrap width=15% bgcolor="Lightgreen"><b>OK</b></td><td width=50%></td></tr>
  | <tr><td nowrap width=35%>Black Drum Cartridge</td><td nowrap width=15% bgcolor="Lightgreen"><b>OK</b></td><td width=50%></td></tr>
  | <tr><td nowrap width=35%>Waste Toner Box</td><td nowrap width=15% bgcolor="Lightgreen"><b>OK</b></td><td width=50%></td></tr>
  | </table></td></tr></table>
  | <br><table border=1 cellpadding=4 cellspacing=0 width=100%><tr><td nowrap>
  | <table border=0 cellpadding=2 cellspacing=0 width=100%>
  | <tr><th scope="col" nowrap align="left" width=35%><b>Paper Trays:</b></th><th scope="col" nowrap align="left" width=15%><b>Status:</b></th><th scope="col" nowrap align="left" width=15%><b>Capacity:</b></th><th scope="col" nowrap align="left" width=35%><b>Size:</b></th></tr>
  | <tr><td nowrap width=35%>MPF</td><td nowrap width=15%><b>Add Paper</b></td><td nowrap width=15%>150 sheets</td><td nowrap width=35%>--</td></tr>
  | <tr><td nowrap width=35%>Tray 1</td><td nowrap width=15% bgcolor="Lightgreen"><b>OK</b></td><td nowrap width=15%>250 sheets</td><td nowrap width=35%>Letter (8.5 x 11&quot;)</td></tr>
  | </table></td></tr></table>
  | <br><table border=1 cellpadding=4 cellspacing=0 width=100%><tr><td nowrap>
  | <table border=0 cellpadding=2 cellspacing=0 width=100%>
  | <tr><th scope="col" nowrap align="left" width=35%><b>Output Tray:</b></th><th scope="col" nowrap align="left" width=15%><b>Status:</b></th><th scope="col" nowrap align="left" width=15%><b>Capacity:</b></th><th scope="col" nowrap width=35%></th></tr>
  | <tr><td nowrap width=35%>Output Tray</td><td nowrap width=15% bgcolor="Lightgreen"><b>OK</b></td><td nowrap width=15%>250 sheets</td><td nowrap width=35%></td></tr>
  | </table></td></tr></table>
  | <br><table border=1 cellpadding=4 cellspacing=0 width=100%><tr><td nowrap>
  | <table border=0 cellpadding=2 cellspacing=0 width=100%>
  | <tr><th scope="col" nowrap align="left" width=35%><b>Cover:</b></th><th scope="col" nowrap align="left" width=15%><b>Status:</b></th><th scope="col" nowrap align="left" width=15%></th><th scope="col" nowrap width=35% ></th></tr>
  | <tr><td nowrap width=35%>Front Cover</td><td nowrap width=15% bgcolor="Lightgreen"><b>Closed</b></td><td nowrap width=15%></td><td nowrap width=35% ></td></tr>
  | <tr><td nowrap width=35%>Right Side Cover</td><td nowrap width=15% bgcolor="Lightgreen"><b>Closed</b></td><td nowrap width=15%></td><td nowrap width=35% ></td></tr>
  | <tr><td nowrap width=35%>Rear Cover</td><td nowrap width=15% bgcolor="Lightgreen"><b>Closed</b></td><td nowrap width=15%></td><td nowrap width=35% ></td></tr>
  | <tr><td nowrap width=35%>DADF Cover</td><td nowrap width=15% bgcolor="Lightgreen"><b>Closed</b></td><td nowrap width=15%></td><td nowrap width=35% ></td></tr>
  | </table></td></tr></table>
  | <br><table border=1 cellspacing=0 class=std_1>
  | <tr><td><table border=0 class=std_2>
  | <tr><td nowrap width=35%><b>Printer Type:</b></td><td nowrap width=65%>Color Laser</td></tr>
  | <tr><td nowrap width=35%><b>Printing Speed:</b></td><td nowrap width=65%>27Pages/Minute (Color), 27Pages/Minute (Monochrome)</td></tr>
  | </table>
  | </td></tr></table>
  | </form>
  | </td></tr></table>
  | </body>
  | </html>
  |  

<!--EndFragment-->
</body>
</html><html>
<head>
<meta http-equiv="Refresh" content="30">
<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
<meta http-equiv="Content-Style-Type" content="text/css">
<STYLE TYPE="text/css"><!--
body { font-family: Arial, Helvetica, sans-serif, Verdana; margin-left:0; margin-right:0; margin-top:0; margin-bottom:0; }
--></STYLE>
<link rel="stylesheet" href="[../common_dell.css](http://192.168.1.120/common_dell.css)" type="text/css">
<title>Dell C2665dnf Color MFP</title>
</head>
<body  bgcolor="#ffffff"  link="#FFFFFF" alink="#FFFFFF" vlink="#FFFFFF">
<table>
<tr><td>
<table border=0 cellpadding=0 cellspacing=0 width=800><tr><td>
<table border=0 cellpadding=0 cellspacing=0>
<tr>
<td valign=top bgcolor=#cdcdcd><div style="background-image: url(../images/lefton.gif  ); border-bottom: 1px solid rgb(255, 255, 255);  width:9px; height:36px;"></div></td>
<td align=center valign=middle bgcolor=#ffffff height=36 nowrap style="white-space: nowrap; border-bottom: 1px solid rgb(255, 255, 255); background-image: url(../images/topon.gif); background-repeat: repeat-x" ><b><font size=-1 color="blue">Printer Status</font></b></td>
<td valign=top bgcolor=#cdcdcd><div style="background-image: url(../images/righton.gif ); border-bottom: 1px solid rgb(255, 255, 255);  width:9px; height:36px;"></div></td>
<td bgcolor="#ffffff" valign="bottom" style="empty-cells:show; border-bottom: 1px solid rgb(0, 0, 0); width: 800; ">&nbsp;</td></tr>
<tr>
<td valign=bottom bgcolor=#ffffff width=9 height=2></td><td valign=bottom bgcolor=#ffffff width=120 height=2></td><td valign=bottom bgcolor=#ffffff width=9 height=2></td><td bgcolor="#ffffff" valign="bottom" height=2></td></tr>
</table>
</td></tr></table>
<table border=0 cellpadding=2 cellspacing=0><tr><td>
<table border=0 cellpadding=2 cellspacing=0><tr>
<td nowrap align=left><b><font size=-1><a href="[status.htm](http://192.168.1.120/status/status.htm)" target="_self">Printer Status</a></font></b>
<b><font size=-1> | <a href="[events.htm](http://192.168.1.120/status/events.htm)" target="_self">Printer Events</a></font></b>
<b><font size=-1> | <a href="[infomation.htm](http://192.168.1.120/status/infomation.htm)" target="_self">Printer Information</a></font></b>
</td></tr></table>
</td></tr></table>
<hr>
<table><tr><td><font size=+2><b>Printer Status - </b></font>
<script language="JavaScript">
<!--
document.write("<input type='button' onClick=window.location='status.htm' value='Refresh'  class=refreshBtn>")
//-->
</script>
<noscript>
<font size=-1><a href="status.htm" target="_self">Refresh</a></font>
</noscript>
</td></tr></table><br><form method="post" action="status.htm"><table border=1 cellpadding=4 cellspacing=0 width=100%><tr><td nowrap>
<table border=0 cellpadding=2 cellspacing=0 width=100%>
<tr><td nowrap width=250></td><td></td></tr>
<tr><td nowrap><b>Cyan Toner Cartridge : OK</b></td><td nowrap></td></tr>
<tr><td nowrap><table frame=border border=2 cellpadding=0 cellspacing=0 bordercolor="cyan"><tr><td nowrap width=80 height=15 bgcolor="cyan">&nbsp;</td><td nowrap width=120 height=15 bgcolor="White">&nbsp;</td></tr></table>
</td><td></td></tr>
<tr><td nowrap><b>Magenta Toner Cartridge : OK</b></td><td nowrap></td></tr>
<tr><td nowrap><table frame=border border=2 cellpadding=0 cellspacing=0 bordercolor="magenta"><tr><td nowrap width=120 height=15 bgcolor="magenta">&nbsp;</td><td nowrap width=80 height=15 bgcolor="White">&nbsp;</td></tr></table>
</td><td></td></tr>
<tr><td nowrap><b>Yellow Toner Cartridge : OK</b></td><td nowrap></td></tr>
<tr><td nowrap><table frame=border border=2 cellpadding=0 cellspacing=0 bordercolor="yellow"><tr><td nowrap width=60 height=15 bgcolor="yellow">&nbsp;</td><td nowrap width=140 height=15 bgcolor="White">&nbsp;</td></tr></table>
</td><td></td></tr>
<tr><td nowrap><b>Black Toner Cartridge : OK</b></td><td nowrap></td></tr>
<tr><td nowrap><table frame=border border=2 cellpadding=0 cellspacing=0 bordercolor="black"><tr><td nowrap width=60 height=15 bgcolor="black">&nbsp;</td><td nowrap width=140 height=15 bgcolor="White">&nbsp;</td></tr></table>
</td><td></td></tr>
</table></td></tr></table>
<br><table border=1 cellpadding=4 cellspacing=0 width=100%><tr><td nowrap>
<table border=0 cellpadding=2 cellspacing=0 width=100%>
<tr><th scope="col" nowrap align="left" width=35%><b>Consumables:</b></th><th scope="col" nowrap align="left" width=15%><b>Status:</b></th><th scope="col" width=50%></th></tr>
<tr><td nowrap width=35%>Cyan Drum Cartridge</td><td nowrap width=15% bgcolor="Lightgreen"><b>OK</b></td><td width=50%></td></tr>
<tr><td nowrap width=35%>Magenta Drum Cartridge</td><td nowrap width=15% bgcolor="Lightgreen"><b>OK</b></td><td width=50%></td></tr>
<tr><td nowrap width=35%>Yellow Drum Cartridge</td><td nowrap width=15% bgcolor="Lightgreen"><b>OK</b></td><td width=50%></td></tr>
<tr><td nowrap width=35%>Black Drum Cartridge</td><td nowrap width=15% bgcolor="Lightgreen"><b>OK</b></td><td width=50%></td></tr>
<tr><td nowrap width=35%>Waste Toner Box</td><td nowrap width=15% bgcolor="Lightgreen"><b>OK</b></td><td width=50%></td></tr>
</table></td></tr></table>
<br><table border=1 cellpadding=4 cellspacing=0 width=100%><tr><td nowrap>
<table border=0 cellpadding=2 cellspacing=0 width=100%>
<tr><th scope="col" nowrap align="left" width=35%><b>Paper Trays:</b></th><th scope="col" nowrap align="left" width=15%><b>Status:</b></th><th scope="col" nowrap align="left" width=15%><b>Capacity:</b></th><th scope="col" nowrap align="left" width=35%><b>Size:</b></th></tr>
<tr><td nowrap width=35%>MPF</td><td nowrap width=15%><b>Add Paper</b></td><td nowrap width=15%>150 sheets</td><td nowrap width=35%>--</td></tr>
<tr><td nowrap width=35%>Tray 1</td><td nowrap width=15% bgcolor="Lightgreen"><b>OK</b></td><td nowrap width=15%>250 sheets</td><td nowrap width=35%>Letter (8.5 x 11&quot;)</td></tr>
</table></td></tr></table>
<br><table border=1 cellpadding=4 cellspacing=0 width=100%><tr><td nowrap>
<table border=0 cellpadding=2 cellspacing=0 width=100%>
<tr><th scope="col" nowrap align="left" width=35%><b>Output Tray:</b></th><th scope="col" nowrap align="left" width=15%><b>Status:</b></th><th scope="col" nowrap align="left" width=15%><b>Capacity:</b></th><th scope="col" nowrap width=35%></th></tr>
<tr><td nowrap width=35%>Output Tray</td><td nowrap width=15% bgcolor="Lightgreen"><b>OK</b></td><td nowrap width=15%>250 sheets</td><td nowrap width=35%></td></tr>
</table></td></tr></table>
<br><table border=1 cellpadding=4 cellspacing=0 width=100%><tr><td nowrap>
<table border=0 cellpadding=2 cellspacing=0 width=100%>
<tr><th scope="col" nowrap align="left" width=35%><b>Cover:</b></th><th scope="col" nowrap align="left" width=15%><b>Status:</b></th><th scope="col" nowrap align="left" width=15%></th><th scope="col" nowrap width=35% ></th></tr>
<tr><td nowrap width=35%>Front Cover</td><td nowrap width=15% bgcolor="Lightgreen"><b>Closed</b></td><td nowrap width=15%></td><td nowrap width=35% ></td></tr>
<tr><td nowrap width=35%>Right Side Cover</td><td nowrap width=15% bgcolor="Lightgreen"><b>Closed</b></td><td nowrap width=15%></td><td nowrap width=35% ></td></tr>
<tr><td nowrap width=35%>Rear Cover</td><td nowrap width=15% bgcolor="Lightgreen"><b>Closed</b></td><td nowrap width=15%></td><td nowrap width=35% ></td></tr>
<tr><td nowrap width=35%>DADF Cover</td><td nowrap width=15% bgcolor="Lightgreen"><b>Closed</b></td><td nowrap width=15%></td><td nowrap width=35% ></td></tr>
</table></td></tr></table>
<br><table border=1 cellspacing=0 class=std_1>
<tr><td><table border=0 class=std_2>
<tr><td nowrap width=35%><b>Printer Type:</b></td><td nowrap width=65%>Color Laser</td></tr>
<tr><td nowrap width=35%><b>Printing Speed:</b></td><td nowrap width=65%>27Pages/Minute (Color), 27Pages/Minute (Monochrome)</td></tr>
</table>
</td></tr></table>
</form>
</td></tr></table>
</body>
</html>
```
