### ISSUE TITLE
Unknown error occurred

### ISSUE THREAD

**Issue by mARTin-B78** [kongo09/hass-dell-printer#7]
Hey
I got a Dell C3765dnf Color MFP that I would like to include in Home Assistant. 

But I get the Error "Unknown error occurred"

So how can I add that model to the supported Models?

**Comment by mARTin-B78** [comment]
Found this [kongo09/dell-printer](https://github.com/kongo09) and [dell-printer-parser](https://pypi.org/project/dell-printer-parser/)

logged into my home assistant docker container command line and executed 

`pip install dell-printer-parser`

What I do not understand is what to do in the "usage" part.
I made a new file and pasted the code in there.
changed the IP to my printers IP, save it as identify.py and typed 
python identify.py 
in the consol.

```
bash-5.1# python identify.py
Traceback (most recent call last):
  File "/config/custom_components/dell_printer/identify.py", line 14, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/config/custom_components/dell_printer/identify.py", line 9, in main
    await dpp.load_data()
  File "/usr/local/lib/python3.10/site-packages/dell_printer_parser/printer_parser.py", line 31, in load_data
    await self._set_language()
  File "/usr/local/lib/python3.10/site-packages/dell_printer_parser/printer_parser.py", line 45, in _set_language
    response.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 404, message='Not found', url=URL('http://192.168.178.9/default.asp?Lang=en-us')

```

**Comment by steveothesane** [comment]
@mARTin-B78 did you ever find a solution to the problem?  One issue I noticed is that as it is calling for data from the printer's home page it is asking for a .asp page.  

> aiohttp.client_exceptions.ClientResponseError: 404, message='Not found', url=URL('http://192.168.178.9/**default.asp**?Lang=en-us')

My printer uses .htm not .asp.  If yours uses a different name for the printer's home page that may be why you are getting the 404 error.  I have no idea where to tell the program to look for index.htm not xxxxx.asp. 

The other is that is is using http not https which I had my printer setup to use.   @kongo09  is there a way in which we can have it use https and not http?
